### ISSUE TITLE
403 error when downloading https://storage.googleapis.com/flash-rank/Splade_PP_en_v1.zip

### ISSUE THREAD

**Issue by superkelvint** [PrithivirajDamodaran/SPLADERunner#1]
Running this code from the README yields a 403 error.

```python
from spladerunner import Expander

expander = Expander('Splade_PP_en_v1', 128)  # pass model, max_seq_len

# Sample passage expansion
sparse_rep = expander.expand(
    "The Manhattan Project and its atomic bomb helped bring an end to World War II. Its legacy of peaceful uses of atomic energy continues to have an impact on history and science.")
print(sparse_rep)
```

requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/flash-rank/Splade_PP_en_v1.zip

**Comment by PrithivirajDamodaran** [comment]
The model bucket has changed, now it's available in HF. Sorry, Pointed back.

Pip upgrade and try, It should work now.

**Comment by superkelvint** [comment]
Confirmed that works! Thanks for the quick turnaround.
