### ISSUE TITLE
Usage directions for performing term expansion

### ISSUE THREAD

**Issue by superkelvint** [PrithivirajDamodaran/SPLADERunner#2]
Is there a set of commands or a notebook that is similar in spirit to https://github.com/naver/splade/blob/main/inference_splade.ipynb that shows how, given a document or query, how to perform term/query expansion?

I could not figure out how to do this given the current API.

**Comment by PrithivirajDamodaran** [comment]
Human readable term expansion:

That particular inference notebook is only for the uninitiated just to understand how the expanded tokens look with weights as a dictionary and most datastores expect data in a different fromat and we cannot index that dict format into popular lucene based datastores or vectordbs and It **"is not how you perform query or document expansion"**.  If you want see a  similar output to get a feel of how the token expansions are, there are plenty of snippets in the model cards [v1](https://huggingface.co/prithivida/Splade_PP_en_v1) , [v2]((https://huggingface.co/prithivida/Splade_PP_en_v2)

Indexable term expansion:

But if you want to expand and index your passages and run queries to test on popular lucene based datastores or vectordbs, the format SPLADERunner currently gives is what you need.  indices and weights where former is the index of the vocab term and weight is the respective weight. 

There is a notebook linked in the same model card above that shows how you run a end to end example with Pinecone.

**Comment by superkelvint** [comment]
That's interesting. I'm a Lucene user myself and how I had used the original Splade library for term expansion was simply by adding the human-readable terms into a separate Lucene field. 

Are you saying that's not the optimal way to index the Splade term expansions? And if so, can you layout the algorithm/procedure instead? Please provide Lucene-specific details if possible.

**Comment by PrithivirajDamodaran** [comment]
Let's start with basics. 

All splade models are basically a MLM based model and my model is just an independent implementation and no different. You don’t need the official splade library to run inference on splade model. 

Option 1: If for your needs you want the terms like it is shown in the other inf notebook i.e. a dictionary you can directly use it with HF - use the snippet shown in the model card. That should sort out your needs. 

No special algorithm of any sort required. Again ! See the code snippets in the model card. 

Option2: Spladerunner library offers a lightweight way to run splade Inf without torch or HF transformer dependency with an output format currently suitable for popular vectordbs as in indices and weights as two different lists. If you need this light weight option a.) you could construct the dictionary from the output or b.) it needs a change to give outputs in different formats. While that’s not a priority at the moment, but we can do the change may be in near future, keep an eye out on this library for future releases.

**Comment by superkelvint** [comment]
Thanks for your reply, but that didn't clarify much for me. 

To start with basics: I have a Lucene index and I want to use the Splade model to perform term expansion at index- and query-time. How would one go about using Spladerunner to do this? My understanding is that this is what you mean by running splade inference right? 

Basically is your answer: you can't right now because its currently built for vector indexes and not lexical indexes?
